apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: apps
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
{{ end }}
